name: release

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: create release bundle
      run: ./.mysys/bin/mysys.sh release
    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        artifacts: "mysys.tar.bz2"
        generateReleaseNotes: true

